[note]
language = "en"
default-title = "Untitled"
filename = "{{id}}-{{slug title}}"
extension = "md"
template = "default.md"
id-charset = "alphanum"
id-length = 4
id-case = "lower"

[tool]
editor = "nvim"
shell = "/bin/zsh"
pager = "less -FIRX"

